export const STOREFRONT_TEMPLATES = {
  catalog: {
    classic: {
      templateKey: "catalog_classic",
      label: "Catalog Classic",
      description: "Tampilan toko umum yang hangat, familiar, dan rapi.",
      hero: "simple_cover",
      sectionOrder: ["hero", "featured_products", "categories", "all_products", "about", "contact"],
      productCard: "standard",
      categoryNav: "chips",
      ctaStyle: "solid",
      density: "comfortable",
      imageRatio: "square",
      mood: "hangat, rapi, mudah dipahami",
      tokens: {
        accent: "#6B4F2A",
        background: "#FBF6EE",
        surface: "#FFFFFF",
        ink: "#2E2418",
        muted: "#7C6B5A",
      },
      designPrompt:
        "Design a warm classic storefront for a small product business. Use familiar ecommerce structure, tidy product cards, soft paper background, clear categories, and direct WhatsApp ordering CTA.",
    },
    modern: {
      templateKey: "catalog_modern",
      label: "Catalog Modern",
      description: "Tampilan clean, elegan, dan digital-forward.",
      hero: "split_banner",
      sectionOrder: ["hero", "categories", "featured_products", "all_products", "testimonials", "contact"],
      productCard: "glass",
      categoryNav: "pill_tabs",
      ctaStyle: "dark",
      density: "airy",
      imageRatio: "portrait",
      mood: "clean, sleek, modern",
      tokens: {
        accent: "#0F172A",
        background: "#F8FAFC",
        surface: "#FFFFFF",
        ink: "#0F172A",
        muted: "#64748B",
      },
      designPrompt:
        "Design a sleek modern storefront with a split hero, airy spacing, crisp product cards, strong typography, subtle gradients, and a premium digital-commerce feel.",
    },
    compact: {
      templateKey: "catalog_compact",
      label: "Catalog Compact",
      description: "Tampilan padat dan ringkas untuk browsing cepat.",
      hero: "minimal_header",
      sectionOrder: ["hero", "categories", "all_products", "contact"],
      productCard: "compact",
      categoryNav: "dropdown",
      ctaStyle: "outline",
      density: "tight",
      imageRatio: "square",
      mood: "efisien, cepat, ringkas",
      tokens: {
        accent: "#334155",
        background: "#FFFFFF",
        surface: "#FFFFFF",
        ink: "#111827",
        muted: "#6B7280",
      },
      designPrompt:
        "Design a compact storefront optimized for quick browsing. Use dense product rows, minimal hero, small cards, efficient spacing, and fast scanability.",
    },
    premium: {
      templateKey: "catalog_premium",
      label: "Catalog Premium",
      description: "Tampilan mewah dengan hero visual besar dan storytelling brand.",
      hero: "luxury_banner",
      sectionOrder: ["hero", "brand_story", "featured_products", "collections", "testimonials", "contact"],
      productCard: "editorial",
      categoryNav: "segmented",
      ctaStyle: "gold",
      density: "airy",
      imageRatio: "portrait",
      mood: "mewah, eksklusif, aspirational",
      tokens: {
        accent: "#D97706",
        background: "#0C0A09",
        surface: "#1C1917",
        ink: "#FAFAF9",
        muted: "#D6D3D1",
      },
      designPrompt:
        "Design a luxury editorial storefront with dark background, gold accents, large visual hero, elegant spacing, curated collections, and aspirational brand storytelling.",
    },
    playful: {
      templateKey: "catalog_playful",
      label: "Catalog Playful",
      description: "Tampilan ceria, ramah, dan lebih ekspresif.",
      hero: "fun_banner",
      sectionOrder: ["hero", "featured_products", "categories", "promo_banner", "all_products", "contact"],
      productCard: "playful",
      categoryNav: "chips",
      ctaStyle: "gradient",
      density: "comfortable",
      imageRatio: "square",
      mood: "ceria, ramah, aktif",
      tokens: {
        accent: "#F97316",
        background: "#FFF7ED",
        surface: "#FFFFFF",
        ink: "#431407",
        muted: "#9A3412",
      },
      designPrompt:
        "Design a cheerful storefront with playful rounded cards, bright warm colors, friendly badges, promo banner, and fun local-business personality.",
    },
  },

  food_menu: {
    classic: {
      templateKey: "food_classic",
      label: "Food Classic",
      description: "Menu sederhana dan familiar seperti katalog restoran.",
      hero: "restaurant_header",
      sectionOrder: ["hero", "today_menu", "categories", "menu_list", "contact"],
      productCard: "menu_row",
      categoryNav: "sticky_tabs",
      ctaStyle: "solid",
      density: "comfortable",
      imageRatio: "square",
      mood: "lezat, akrab, mudah pesan",
      tokens: {
        accent: "#B45309",
        background: "#FFFBEB",
        surface: "#FFFFFF",
        ink: "#451A03",
        muted: "#92400E",
      },
      designPrompt:
        "Design a friendly restaurant menu storefront. Use menu rows, appetizing warm colors, easy categories, today menu highlight, and clear WhatsApp order CTA.",
    },
    modern: {
      templateKey: "food_modern",
      label: "Food Modern",
      description: "Tampilan menu kekinian seperti online food brand.",
      hero: "full_bleed_food",
      sectionOrder: ["hero", "promo_banner", "today_menu", "categories", "menu_grid", "contact"],
      productCard: "food_card_modern",
      categoryNav: "pill_tabs",
      ctaStyle: "dark",
      density: "airy",
      imageRatio: "square",
      mood: "fresh, modern, appetite-inducing",
      tokens: {
        accent: "#EA580C",
        background: "#FFF7ED",
        surface: "#FFFFFF",
        ink: "#1F2937",
        muted: "#9A3412",
      },
      designPrompt:
        "Design a modern food storefront with large mouth-watering hero, bold menu cards, promo strip, warm gradients, and online food-brand energy.",
    },
    compact: {
      templateKey: "food_compact",
      label: "Food Compact",
      description: "Menu cepat untuk order praktis.",
      hero: "minimal_food_header",
      sectionOrder: ["hero", "today_menu", "menu_list", "contact"],
      productCard: "menu_dense_row",
      categoryNav: "dropdown",
      ctaStyle: "outline",
      density: "tight",
      imageRatio: "square",
      mood: "cepat, praktis, efisien",
      tokens: {
        accent: "#C2410C",
        background: "#FFFFFF",
        surface: "#FFFFFF",
        ink: "#111827",
        muted: "#78716C",
      },
      designPrompt:
        "Design a fast compact food menu optimized for quick ordering. Use dense rows, small thumbnails, clear prices, and minimal distractions.",
    },
    premium: {
      templateKey: "food_premium",
      label: "Food Premium",
      description: "Tampilan restoran premium dengan visual hero besar.",
      hero: "chef_story_banner",
      sectionOrder: ["hero", "signature_menu", "brand_story", "menu_grid", "testimonials", "contact"],
      productCard: "editorial_food",
      categoryNav: "segmented",
      ctaStyle: "gold",
      density: "airy",
      imageRatio: "landscape",
      mood: "premium dining, elegant, polished",
      tokens: {
        accent: "#F59E0B",
        background: "#111827",
        surface: "#1F2937",
        ink: "#FFFBEB",
        muted: "#FDE68A",
      },
      designPrompt:
        "Design a premium dining storefront with cinematic hero, signature menu section, elegant dark surface, gold accents, and polished restaurant storytelling.",
    },
    playful: {
      templateKey: "food_playful",
      label: "Food Playful",
      description: "Tampilan makanan yang cerah, fun, dan menggugah selera.",
      hero: "fun_food_banner",
      sectionOrder: ["hero", "promo_banner", "today_menu", "categories", "menu_grid", "contact"],
      productCard: "fun_food_card",
      categoryNav: "chips",
      ctaStyle: "gradient",
      density: "comfortable",
      imageRatio: "square",
      mood: "fun, colorful, tasty",
      tokens: {
        accent: "#FB923C",
        background: "#FFF7ED",
        surface: "#FFFFFF",
        ink: "#431407",
        muted: "#C2410C",
      },
      designPrompt:
        "Design a cheerful food storefront with bright warm colors, playful stickers, rounded food cards, visible promo banner, and fun WhatsApp ordering flow.",
    },
  },

  services: {
    classic: {
      templateKey: "services_classic",
      label: "Services Classic",
      description: "Tampilan layanan yang jelas dan terpercaya.",
      hero: "service_intro",
      sectionOrder: ["hero", "service_list", "benefits", "about", "contact"],
      productCard: "service_standard",
      categoryNav: "none",
      ctaStyle: "solid",
      density: "comfortable",
      imageRatio: "landscape",
      mood: "jelas, terpercaya, profesional",
      tokens: {
        accent: "#2563EB",
        background: "#EFF6FF",
        surface: "#FFFFFF",
        ink: "#1E3A8A",
        muted: "#475569",
      },
      designPrompt:
        "Design a trustworthy service storefront with clear service list, professional copy, benefits section, clean contact CTA, and friendly local-service tone.",
    },
    modern: {
      templateKey: "services_modern",
      label: "Services Modern",
      description: "Tampilan jasa modern seperti startup service page.",
      hero: "split_service_hero",
      sectionOrder: ["hero", "benefits", "service_list", "testimonials", "contact"],
      productCard: "service_modern",
      categoryNav: "pill_tabs",
      ctaStyle: "dark",
      density: "airy",
      imageRatio: "landscape",
      mood: "clean, modern, professional",
      tokens: {
        accent: "#0F172A",
        background: "#F8FAFC",
        surface: "#FFFFFF",
        ink: "#0F172A",
        muted: "#64748B",
      },
      designPrompt:
        "Design a modern service landing page with split hero, benefit cards, clean service grid, professional trust signals, and strong consultation CTA.",
    },
    compact: {
      templateKey: "services_compact",
      label: "Services Compact",
      description: "Tampilan ringkas untuk daftar layanan cepat.",
      hero: "minimal_service_header",
      sectionOrder: ["hero", "service_list", "contact"],
      productCard: "service_dense",
      categoryNav: "none",
      ctaStyle: "outline",
      density: "tight",
      imageRatio: "landscape",
      mood: "ringkas, cepat, to the point",
      tokens: {
        accent: "#334155",
        background: "#FFFFFF",
        surface: "#FFFFFF",
        ink: "#111827",
        muted: "#6B7280",
      },
      designPrompt:
        "Design a compact service storefront for fast decision-making. Use minimal hero, dense service rows, direct pricing, and quick contact action.",
    },
    premium: {
      templateKey: "services_premium",
      label: "Services Premium",
      description: "Tampilan jasa eksklusif untuk konsultasi, salon, klinik, dan layanan premium.",
      hero: "luxury_service_banner",
      sectionOrder: ["hero", "about", "service_list", "testimonials", "contact"],
      productCard: "service_editorial",
      categoryNav: "segmented",
      ctaStyle: "gold",
      density: "airy",
      imageRatio: "landscape",
      mood: "eksklusif, elegan, premium",
      tokens: {
        accent: "#D97706",
        background: "#0C0A09",
        surface: "#1C1917",
        ink: "#FAFAF9",
        muted: "#D6D3D1",
      },
      designPrompt:
        "Design a premium service storefront with elegant dark hero, editorial service cards, trust-focused storytelling, gold accents, and exclusive consultation feel.",
    },
    playful: {
      templateKey: "services_playful",
      label: "Services Playful",
      description: "Tampilan layanan yang ramah, ringan, dan approachable.",
      hero: "friendly_service_banner",
      sectionOrder: ["hero", "service_list", "benefits", "faq", "contact"],
      productCard: "service_playful",
      categoryNav: "chips",
      ctaStyle: "gradient",
      density: "comfortable",
      imageRatio: "landscape",
      mood: "ramah, santai, approachable",
      tokens: {
        accent: "#7C3AED",
        background: "#F5F3FF",
        surface: "#FFFFFF",
        ink: "#3B0764",
        muted: "#6D28D9",
      },
      designPrompt:
        "Design a friendly playful service storefront with soft purple accents, rounded cards, approachable copy, simple benefits, FAQ section, and casual consultation CTA.",
    },
  },
};

export function resolveStorefrontTemplate(mode = "catalog", style = "classic") {
  const safeMode = STOREFRONT_TEMPLATES[mode] ? mode : "catalog";
  const modeTemplates = STOREFRONT_TEMPLATES[safeMode];
  return modeTemplates[style] || modeTemplates.classic || STOREFRONT_TEMPLATES.catalog.classic;
}

export function getStorefrontTemplateOptions() {
  return Object.entries(STOREFRONT_TEMPLATES).flatMap(([mode, styles]) =>
    Object.entries(styles).map(([style, template]) => ({
      mode,
      style,
      ...template,
    }))
  );
}
